// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://uxtwfprczjqeulpazdau.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dHdmcHJjempxZXVscGF6ZGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA4ODk4OTcsImV4cCI6MjA0NjQ2NTg5N30.ZvlpaalhFScQIwWFHxh2X9PkUlh0mpXtP8KrcsZBfpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);